### ISSUE TITLE
React Router Support

### ISSUE THREAD

**Issue by 0ctan33** [enszrlu/NextStep#11]
Hey Alex! 

Solid library! We're porting this to React Router + shadcn for our own internal use & was wondering if you'd be interested in adding support for React Router in the official implementation or if you would be ok for us to release a new RR version based off NextStep / Onborda?

Thanks!

**Comment by enszrlu** [comment]
Hi, this was something I was planning to support. I will tackle this in next two days and release the react router support.

**Comment by 0ctan33** [comment]
Noted, thanks !

**Comment by enszrlu** [comment]
@0ctan33 I released v2 beta. Can you please test it out by installing nextstepjs@beta ? 

https://www.npmjs.com/package/nextstepjs/v/2.0.0-beta.5

See above for details how to use custom adapters for routing. If you are using vite, you will need to update your vite config with below

`optimizeDeps: {
    include: ['nextstepjs']
  },
  ssr: {
    noExternal: ['nextstepjs']
  }`

Example:
`import { reactRouter } from "@react-router/dev/vite";
import autoprefixer from "autoprefixer";
import tailwindcss from "tailwindcss";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  css: {
    postcss: {
      plugins: [tailwindcss, autoprefixer],
    },
  },
  plugins: [reactRouter(), tsconfigPaths()],
  optimizeDeps: {
    include: ['nextstepjs']
  },
  ssr: {
    noExternal: ['nextstepjs']
  }
});
`


Also can you please let me know which one you are using?


    "react-router": "^7.0.2",
    "react-router-dom": "^7.0.2"

I am using react-router-dom at the moment but I can switch to react-router easily as well.

**Comment by 0ctan33** [comment]
hi @enszrlu thanks will take a look. 

RR v7 has all been flattened into react-router & react-router-dom is just a re-export of everything. unless you want to target <7 I think better to just use react-router imports
