### ISSUE TITLE
Error on 'viewportID' when creating steps

### ISSUE THREAD

**Issue by tylerjusfly** [enszrlu/NextStep#5]
Error: Object literal may only specify known properties, and 'viewportID' does not exist in type 'Step'.ts(2353)
(property) viewportID: string

Copied code from right here.
https://github.com/enszrlu/NextStep-Website/blob/main/src/lib/steps.tsx

**Comment by enszrlu** [comment]
Please just delete the viewportID property from any steps in that array.

Website includes the code from v1.1.0 beta, that is why it is happening.

You can copy V.1.0 code from here. 

https://nextstepjs.vercel.app/docs?tab=examples&version=1.0.x

If you would like to use beta instead with new features. Install the package like this. 

```
npm install nextstepjs@beta
```

**Comment by tylerjusfly** [comment]
Thanks.
