### ISSUE TITLE
Styling overriding

### ISSUE THREAD

**Issue by GermanDZ** [enszrlu/NextStep#6]
Have you thought on how to provide a way to override style to titles, progress bars, buttons, etc?

Just by adding some classes to name the elements will be great to override them in global.css

**Comment by enszrlu** [comment]
You can provide your own card component and customize everything to your app's needs. Please have a look at this in docs and let me know if it satisfy your need 😊

[https://nextstepjs.vercel.app/docs?tab=examples&version=1.0.x](https://nextstepjs.vercel.app/docs?tab=examples&version=1.0.x)

**Comment by GermanDZ** [comment]
Yeah, I thought that was too much but actually makes a lot of sense, just by copy-pasting the default card and tweak any details is better solution than adding styles/variants/modifiers/options to the default Card.

Thanks a lot.
