### ISSUE TITLE
Nextsetp Card not aligning in middle

### ISSUE THREAD

**Issue by blzn50** [enszrlu/NextStep#9]
I checked the demo website and it seems the `div` with `data-name="nextstep-pointer"` has _width_ and _height_ property even though those are not set in the NextStep component. This makes the Card component to appear in the middle. When I used the library, I don't get the height and width property due to which the card appears cut off on the right side. Is there a way to pass styling to NextStep component to fix this?

My implementation
<img width="708" alt="Screenshot 2024-11-07 at 23 57 53" src="https://github.com/user-attachments/assets/67ceef72-31aa-4250-9d1a-ce702c11a469">

Implementation in demo site
<img width="1097" alt="Screenshot 2024-11-08 at 0 03 26" src="https://github.com/user-attachments/assets/4034eecc-0477-4f64-9524-cf4504c01ec1">

I am using Pages router.

**Comment by enszrlu** [comment]
It should appear on the middle without any additional work. Can you please check if you wrapped the entire app and if there is any relative  component in between?

It is always better to copy paste example custom card from the website and modify it to your needs.
https://nextstepjs.com/docs?tab=examples&version=1.2.x%20(latest)
